In [17]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)

a.astype(int)
np.average(a,axis=1)
# a = np.arange(3).reshape(1,3)
# print(a)
# b = np.arange(3).reshape(1,3)
# c = np.vstack((a,b))
# print(c)
# d = np.zeros((1,3))
# print(np.vstack((d,a)))

a[1].append(33)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [13]:
import cv2
points = np.arange(16).reshape(2,8)
out = np.zeros((1,4))
cv2.fitLine(points,out,distType=cv2.CV_DIST_L2)

AttributeError: module 'cv2' has no attribute 'cv'

In [15]:
print('ss'+'ss')
2**3
sqrt(4)

ssss


NameError: name 'sqrt' is not defined

In [ ]:
1/2
a = float('inf')
b = float('inf')
1==b

In [40]:
print(a.shape)
print(a.itemsize)
print(a.size)
print(a.ndim)

(3, 5)
8
15
2


In [41]:
type(a)

numpy.ndarray

In [42]:
b = np.array([[3,4],[4,5]])
print(b)
print(b.shape)
type(b)
b.reshape(2,2)
b.shape

[[3 4]
 [4 5]]
(2, 2)


(2, 2)

In [43]:
np.zeros((4,5,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [44]:
c = np.arange(0,10,2)
print(type(c))
print(c)
c.reshape(1,5)

d = [1,2]
print(type(d))
e = (2,3)
type(e)

<class 'numpy.ndarray'>
[0 2 4 6 8]
<class 'list'>


tuple

In [45]:
x = np.linspace(0,2,9,dtype=np.float64)
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736]])

In [46]:
# np.set_printoptions(threshold='nan')
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [47]:
##Basic opration

In [48]:
import numpy as np
a = np.random.random((2,3))
a

array([[ 0.70304317,  0.89449312,  0.86708617],
       [ 0.56378619,  0.4040289 ,  0.8038265 ]])

In [49]:
b = np.ones((2,3))
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [50]:
c = a+b
c.sum(axis=1)

array([ 5.46462246,  4.77164159])

In [51]:
b.cumsum(axis=0)

array([[ 1.,  1.,  1.],
       [ 2.,  2.,  2.]])

In [52]:
np.add(a,b)

array([[ 1.70304317,  1.89449312,  1.86708617],
       [ 1.56378619,  1.4040289 ,  1.8038265 ]])

In [53]:
np.exp(b)

array([[ 2.71828183,  2.71828183,  2.71828183],
       [ 2.71828183,  2.71828183,  2.71828183]])

In [60]:
a = np.arange(10)
a = a**2
a[2:4]
print(a[-1])
a[::-1]
a[:6:4]=100
a

81


array([100,   1,   4,   9, 100,  25,  36,  49,  64,  81])

In [70]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b
print(b)
b[:,:]
# for row in b.flat:
#     print(row)
    
b.ravel()
b.reshape(4,5)
b.T

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

In [79]:
a = 10 * np.random.random((2,2))
print(a)
np.floor(a)
b = 10*np.random.random((2,2))
np.vstack((a,b))
np.hstack((a,b))
np.column_stack((a,b))

[[ 2.61088201  8.06272733]
 [ 9.63008558  3.0651299 ]]


array([[ 2.61088201,  8.06272733,  0.11618392,  0.08188942],
       [ 9.63008558,  3.0651299 ,  9.2902402 ,  5.18561033]])

In [92]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a.shape)
print(np.vstack((a,b)))
print(np.column_stack((a,b)))
a[:,np.newaxis]
np.column_stack((a[:np.newaxis],b[:,np.newaxis]))
from numpy import newaxis
np.vstack((a[:,newaxis],b[:,newaxis]))

(3,)
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [100]:
np.c_[1:5]

array([[1],
       [2],
       [3],
       [4]])

### hsplit

In [103]:
a = np.floor(10*np.random.random((2,10)))
print(a)
np.hsplit(a,(3,))

[[ 4.  7.  8.  6.  7.  6.  6.  7.  6.  8.]
 [ 1.  2.  4.  6.  7.  4.  8.  3.  7.  4.]]


[array([[ 4.,  7.,  8.],
        [ 1.,  2.,  4.]]), array([[ 6.,  7.,  6.,  6.,  7.,  6.,  8.],
        [ 6.,  7.,  4.,  8.,  3.,  7.,  4.]])]